import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import NextTopLoader from 'nextjs-toploader';

import "primereact/resources/themes/lara-dark-teal/theme.css"
import { PrimeReactProvider } from 'primereact/api';




const inter = Inter({ subsets: ["latin"] });
import BootstrapClient from "./components/BootstrapClient";
import Header from "./components/Header";
import Footer from "./components/Footer";
export const metadata = {
  title: "API DummyJson",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      
     <body className={`bg-fondo text-white-50 ${inter.className}`}>
      <Header />
      <main>
      <NextTopLoader />
        {children}
        </main>
      <Footer />
      <BootstrapClient/>
      </body>
      
    </html>
  );
}
